version: "3.8"

services:
  airbed:
    container_name: airbed
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./airbed:/airbed
    command: >
      sh -c "python manage.py wait_for_db && 
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

    environment:
      - DB_HOST=db
      - DB_NAME=airbed
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:16.0-alpine3.18
    container_name: "postgres"
    ports:
      - "54320:5432"
    environment:
      - POSTGRES_DB=airbed
    env_file:
      - .env
