# Generated by Django 2.2.6 on 2020-08-19 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200819_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='main.Property'),
        ),
    ]
